version: '3.7'
services:
  dicom-to-mesh:
    build: .
    container_name: dtm
    tty: true
    volumes:
      - ${ROOT_DIR}/dicom:/app/vertebra/dicom:ro
      - ${ROOT_DIR}/mesh:/app/vertebra/mesh:rw
      - ${ROOT_DIR}/scripts:/app/vertebra/scripts:ro